services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: healthy_habits_tracker:local_dev
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: healthy_habits_tracker:local_dev
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: healthy_habits_tracker:local_dev
