# Generated by Django 5.2.4 on 2025-07-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время выполнения"
            ),
        ),
    ]
